# Site settings
title: "Notes of Some Books"
email: neshmailsu@gmail.com
description: ""
baseurl: ""
url: "https://neshkatrapati.github.io/notes-of-books/"
title_description: ""
title_image: "http://www.gravatar.com/avatar/b1ff97476385af8b5e6977593ba57765.jpg?s=500&r=g"
google_analytics: ""
github_repository: https://github.com/neshkatrapati
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: neshmailsu
github_username:  neshkatrapati

# Footer
footer_left: ""
footer_right: "&lt;/&gt; on <a href=\"https://github.com/neshkatrapati/\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
